### ISSUE TITLE
Přesun v záložkách výpisu z databáze knihovny

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#12]
-Ze Záložky Podrobné přesunout část Web do záložky Kontakty (a dát jej na první místo nad telefony)
-Záložku Podrobné zcela odstranit
-Spojit záložky Služby a Projekty do "Služby a projekty", a projekty dát až nakonec.
-také navrhuji změnit pořadí záložek, aby šly za sebou: Služby a projekty, Pobočky (ty se zobrazují jen u knihoven, které je mají) a Kontakty

**Comment by honza-rychtar** [comment]
Stejne jako u pobocek by i tab _kontakty_, resp. _sluzby a projekty_ mel byt zobrazen jen pokud knihovna nejake kontakty, resp. sluzby nebo projekty obsahuje.

**Comment by honza-rychtar** [comment]
Vse jsem takto udelal, jen u poradi jsem nechal Kontakty na prvnim miste - Kontakty se zobrazuji vzdy, zbyle taby jen pokud maji nejaky obsah (pobocky, sluzby a projekty).
Tak at je vzdy aktivni stejny tab. Bylo by asi matouci, pokud by se zobrazoval ruzny kontext v zavislosti na vyplnenych datech. Takze se u kazde knihovny zobrazi kontakty a podle dat je mozne kontext pres tab menit.
