### ISSUE TITLE
Razeni podle priority

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#13]
Priorita bude urcena typem knihovny (krajska, mestska, ..). Defaultne se budou vysledky (i v naseptavaci) radit podle prioriy. Knihovny se stejnou prioritou se dal seradi podle nazvu.
Stavajici razeni podle nazvu bude mozne vynutit.

**Comment by honza-rychtar** [comment]
Existuje nasledujicich 12 typu knihoven:
10  "NK" - národní knihovna
20  "KK" - krajská knihovna
30  "MK" - městská knihovna
40  "VŠ" - vysokoškolská knihovna
50  "OK" - obecní knihovna
60  "AK" - knihovna státní správy
70  "VK" - knihovna výzkumného ústavu
80  "KI" - knihovna kulturní instituce
90  "SP" - ostatní specializovaná knihovna
100 "LK" - lékařská knihovna
110 "ŠK" - školní knihovna
120 "CK" - církevní knihovna

Cislo na zacatku urcuje prioritu, podle ktere se vysledky seradi vzestupne.
Prosim o pripominky k urceni priorit - seradil jsem to takto podle sebe .... 
Ma skolni knihovna vyssi prioritu nez cirkevni? Ma knihovna statni spravy vyssi prioritu nez knihovna kulturni instituce? Atd.

Priorita je ted uplatnena v naseptavaci a ve vysledcich hledani. 
Takze kdyz zadam "měst", tak je v naseptavaci MKP hned na prvnim miste.
Pokud vyhledam "Městská knihovna"
http://info.knihovny.cz/libraries?q=M%C4%9Bstsk%C3%A1+knihovna
Tak mam taky na prvnim miste MKP a taky jsem umele snizil prioritu knihovnam, ktere maji nazev "Městská knihovna" bez dalsiho upresneni. Takze tyto se seradi az nakonec, resp. za vsechny knihovny typu mestska knihovna.

Taky zkuste zadat treba "národní" a podivat se, co naseptavac nabizi - jestli je to razeni takove, jak byste ocekavali.

**Comment by zabak** [comment]
konkrétně u slova národní bych dal Národní technickou knihovnu na 2 a Národní lékařskou na 3. místo, pak Národní archiv, muzeum, galerii atd. Ale všimpl jsem si, že jsou v našeptávači duplicitní výskyty národní lékařské i technické knihovny (a asi i jiných).

**Comment by honza-rychtar** [comment]
@zabak Musi to byt obecne.
Napr. NTK je typu "ostatní specializovaná knihovna" 
a Narodni archiv je typu "knihovna státní správy" - proto je pred NTK podle priority.
Muzu to prehodit, ale pozor - nemel by se vyzdvihovat typ kvuli jedne velke instituci s timto typem.
Napr. vyzdvihnuti typu lekarska knihovna kvuli NLK pak povede k tomu, ze dalsich 200 malickych lekarskych knihoven bude pred vyznamnejsimi institucemi.
Pravidel pro prirazeni priority muzu pridat vic, jako napr. zvysit prioritu pokud nazev obsahuje "narodni", ale nevim no. 

Duplicity tam vznikly kdyz jsem pridal prioritu.
Postrgres mi nedovoli seradit podle sloupce, ktery neni v selektu - takze jsem musel pridat prioritu do selektu ... no a na to je pouzity distinct - na dvojici (nazev, priorita).
Takze se tam ted muzou vyskytovat duplicity v nazvu, pokud maji dve knihovny stejny nazev ale jinou prioritu, tj. jsou jineho typu. 
Tak je tomu u "Národní lékařská knihovna"
1) http://info.knihovny.cz/libraries/ABE015 - typ "lékařská knihovna"
2) http://info.knihovny.cz/libraries/ABA008 - typ "knihovna státní správy"

Pokusim se to nejak obejit.
