### ISSUE TITLE
Odkazy na projekty

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#15]
Pridat k projektum take odkazy na web projektu, at se na ne da z webu prokliknout.

**Comment by vodomilka** [comment]
Ještě upřesním: Vytvoříme statickou stránku, kde budou všechny projekty stručně popsány (na jeden odstavec max.) a až zde budou odkazy na weby projektů, abychom uživatele moc brzy neodváděli pryč ze serveru. Podobně by existovala statická stránka s popisky služeb.

**Comment by honza-rychtar** [comment]
Nemela by to byt  staticka stranka.
Projekty jsou nejak definovany (nazev, kod) a ulozeny v databazi. 
Pridal jsem k nim popis a url.
Vysledek vypada takto: http://info.knihovny.cz/projects
Je to seznam vsech projektu (nazev, popis, odkaz na web projektu).
Predpokladam, ze budou pribyvat nove projekty, ktere se pridaji i do ciselnku k ADR bazi.
Takze projekty pak umoznim pridavat a editovat v aplikaci (podobne jako akce). 
Taky by se to melo rozsirit o anglicky nazev a popis.

Na projekty se pak odkazuje z detailu knihovny, napr. http://info.knihovny.cz/libraries/ABG001 -> sluzby a projekty -> u projektu je odkaz "vice zde", ktery vede na stranku se seznamem projektu a stranka automaticky "poskoci" na vybrany projekt.

Behem tydne dodelam filtry, kde se bude dat filtrovat take podle zapojeni do projektu.
Na strance se seznamem projektu pak pridam pro kazdy projekt P odkaz "zobrazit zapojene knihovny", ktery skoci do vyhledavani s predvybranym kriteriem - knihovna je zapojena do projektu P.

Odkaz na seznam projektu by se mel jeste pridat do paticky - tu musime jeste promyslet a propijit s beta.knihovny.cz 

Popisy a url projektu jsem dohledaval rucne, takze zejmena popisy jsou jen narychlo vykousnute casti z webu projektu nebo jinych zdroju.

**Comment by vodomilka** [comment]
Není mi jasné, proč by popis projektů neměl být statická stránka. Nyní není předpoklad, že tam bude rostoucí seznam projektů, protože uživateli, který není knihovník, jsou tyto projekty víceméně neznámé a nelze očekávat, že si o nich každý bude číst a podle toho hledat.

Pokud by bylo možné projekty obalit ve výpisu u knihověn URL linkem, jako jste obalil u webů knihoven, budu ráda, přišlo by mi to lepší než opakovat větu "více zde".

**Comment by honza-rychtar** [comment]
Obalil jsem projekty linkem.
