### ISSUE TITLE
Vyhledávání podle adresy

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#18]
Narazila jsem při vyhledávání podle adresy, že se při zadání dotazu "Praha" vrátí pouze 31 výsledků, ale pokud zadám např. Praha 1 vrátí se 127 výsledků. Šlo by nějak vyrešit, aby se při zadání Praha zobrazily knihovny opravdu z celé Prahy? 
Nevím, čím tato nesourodost vznikla, když jsem hledala v ADR NK, zda mají adresu udanou jinak knihovny, které se zobrazí po zadání Praha a nebo Praha 2, tak jsem si ničeho odlišného nevšimla.
Je možné, že podobný problém vznikne i u jiných měst?

**Comment by honza-rychtar** [comment]
Hledani podle mesta se resilo pres presnou shodu na mesto, ktere je soucasti adresy. U Prahy se uvadi mestske casti, takze presna shoda fungovala jen pri presnem zadani (Praha 1, Praha 2, ...). Tech 31 vysledku vlastne nebyly nalezy na shodu mesta, ale na shodu nazvu - u nazvu staci, kdyz je hledany retezec nekde v nazvu obsazen.
Zmenil jsem to,  ze se mesto hleda tak, aby mesto na hledany retezec zacinalo, takze ted pri hledani "Praha" to najde vsechny knihovny, kde mesto na retezec "Praha" zacina, tj. Praha 1, Praha 2, ...
