### ISSUE TITLE
V jakém formátu zadávat otvírací dobu?

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#19]
Úpravy formuláře v ADR pomocí widgetů prý nejsou možné do konce roku, takže opravdu se bude otvírací doba zadávat ručně, jaký formát považujete za optimální? Ať tento formát zahrneme do manuálu pro knihovny, podle kterého jej budou vyplňovat. Třeba aby to bylo i výhledově použitelné?
Např:? 8:00-18:00 (s mezera mi bez nich?). Jak to zapsat, pokud je polední pauza, třeba oddělit údaje středníkem? (8:00-12:00;13:00-18:00).

**Comment by honza-rychtar** [comment]
Nejlepe hh:mm-hh:mm, takze bez mezery a s predsazenyma nulama. Napr. 08:00-18:00
Takto se z toho da doba vzit, OD, DO ulozit zvlast a pripadne nakonec v prezentaci zobrazit jinak.

Pokud vubec poleni pauzy resit, pak souhlasim se strednikem jako oddelovacem:
hh:mm-hh:mm;hh:mm-hh:mm

**Comment by vodomilka** [comment]
OK, předám tuto informaci do manuálu pro vyplňování formuláře ADR.
