### ISSUE TITLE
Doplnit vedlejsi nazvy

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#2]
Pouze hlavni nazvy NAZ$a nestaci.
Napr. "Masarykova univerzita" - http://czech-libraries.herokuapp.com/libraries?q=Masarykova+univerzita
ma 17 zaznamu a vsechny maji stejny hlavni nazev.

V hledani, vysledcich hledani a v detailu knihovny pouzit i vedlejsi nazvy
Napr.
NAZ$b - Filozofická fakulta
NAZ$c - Ústřední knihovna

**Comment by vodomilka** [comment]
Nejsem si jistá, zda je to dotaz na mne, nicméně při testování adresáře vidíme, že je problém, že našeptávač nabízí spoustu výrazů Městská knihovna  http://czech-libraries.herokuapp.com/libraries?q=M%C4%9Bstsk%C3%A1+knihovna ) , protože knihovny uvádějí místo působiště až třeba do adresy, ačkoli oficiálně se třeba jmenují Městská knihovna Litvínov apod. 

Vzhledem k tomu, že připravujeme pro knihovny manuál, co a jak vyplňovat v Adresáři knihoven v Alephu, tak to je zrovna jedno z polí, u nichž můžeme apelovat na zlepšení.

**Comment by honza-rychtar** [comment]
Konkretne u "Mestska knihovna" je to problem, protoze nemaji vyplneny NAZ$b,c. Takze to rozlisit nepujde - knihovny si budou muset zmenit NAZ$a
Predelam naseptavac, at nabizi pouze unikatni vysledky.

**Comment by honza-rychtar** [comment]
Vedlejsi nazvy zobrazovat v seznamu nalezenych vysledku a v detailu knihovny,

**Comment by vodomilka** [comment]
Jak jsem psala dnes jinde - s variantními názvy je problém, že často nejsou vyplněné. Během týdne od nás má jít doporučení, co požadujeme, aby knihovny v názvech měnily. Máme tedy doporučit vyplnění Varianty názvu? A to jak knihovnám, které zatím vypadají jako pouze Městské či obecní, tak univerzitním knihovnám.

**Comment by vodomilka** [comment]
Nicméně při zobrazování dat s komplikovanými názvy jsem narazila na to, že to u nás na info.... vypadá jen jako "Masarykova univerzita" http://czech-libraries.herokuapp.com/libraries/BOD118 se na ADR tváří, že má vyplněný rozsáhlý název: http://aleph.nkp.cz/F/I386HE6QULUE28H4SB8FGGF8D1U32XF2S22J5T79H28QDA42V2-60083?func=full-set-set&set_number=062973&set_entry=000001&format=030

**Comment by honza-rychtar** [comment]
Pridal jsem sbirani cele struktury nazvu (NAZ$a,b,c).
V detailu se ted zobrazi hlavni nazev a pod nim (pokud existuje) vedlejsi nazev ve tvaru NAZ$b - NAZ$c
Napr. http://info.knihovny.cz/libraries/BOD018
Masarykova univerzita
Fakulta informatiky - Knihovna
Vedlejsi nazvy se vypisou i ve vysledcich hledani, napr.
http://info.knihovny.cz/libraries?q=Masarykova+univerzita

Varianty nazvu jsou pak neco jineho, odtama se berou anglicke nazvy. Ty se sbirani taky a vcetne vedlejsich nazvu se zobrazi v anglicke verzi - http://info.knihovny.cz/libraries/BOD018?locale=en
