### ISSUE TITLE
Přesunout adresu dolů do záložky Kontakt

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#20]
Jednak ji adresu v záložce kontakt lidé hledají (a nahoře ji přehlédnou) a také v situaci, kdy je opravdu miniknihovna takřka bez jakýchkoli údajů, tak v tuhle chvíli není v Záložce kontakt zobrazené vůbec nic, takže tím by se to vyřešilo.
Např. zde: http://info.knihovny.cz/libraries/ZNG525

**Comment by honza-rychtar** [comment]
Ok, ale nechal bych ji i nahore - muze byt?

**Comment by vodomilka** [comment]
Jo, myslím, že tahle duplicita neuškodí, děkuji za návrh.
