### ISSUE TITLE
OTD$6 se nezobrazuje

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#22]
Zdravím, tak pan Záhořík s paní Svobodovou vše nově kontrolovali a z jejich strany by se měla exportovat všechna data, včetně soboty. Nenašli u sebe problém. 
Není možné, že se data u nás ještě neaktualizovala a proto nezobrazují soboru? Jak často vlastně probíhá aktualizace dat mezi info.knihovny.cz a adresářem NK?

**Comment by honza-rychtar** [comment]
OTD$6 v zaznamu pres Aleph X-Services porad chybi.
Postup pro MKP:

1) V Alephu http://aleph.nkp.cz/F/?func=direct&doc_number=000000687&local_base=ADR&format=001
jde videt, ze zaznam OTD$6 obsahuje (hodnota 13:00 - 18:00).

2) Takto se pres Aleph X-Service zeptam na zaznamy se siglou abg001:
http://aleph.nkp.cz/X?op=find&find_code=wrd&base=ADR&request=sig=abg001
Z vysledku vemu XYZ z tohoto radku <set_number>XYZ</set_number>

3) Pak pres dotaz s doplnenym XYZ dostanu zaznam:
http://aleph.nkp.cz/X?op=present&set_entry=000000001&format=marc&set_no=XYZ
A tady jde videt, ze OTD obsahuje 1,2,3,4,5,7,p
OTD$6 chybi

Kroky 2) a 3) se daji nahradit jednim dotazem v adresari - http://info.knihovny.cz/feeder/show/abg001
Nicmene pres kroky 2) a 3) jde videt, ze chyba neni na me strane.

**Comment by vodomilka** [comment]
Díky za zprávu a popis, budu to opět urgovat směrem na pana Záhoříka.

**Comment by vodomilka** [comment]
Zdravím, s polem OTD$6 je problém v Alephu, který se zatím nepodařilo vyřešit. Teoreticky by to fungovat mělo a nebyla zjištěna příčina, proč zrovna tohle pole nejde do exportu. Stay tuned :-)

**Comment by vodomilka** [comment]
Zdravím, dorazila zpráva od pana Záhoříka:

zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
Aleph z nejakeho duvodu na vystupu podpole odfiltruje. Nevim proc a myslim, ze s tim nedokazu nic udelat. 

Mluvil jsem o tom s kolegy tady v Brne a jedine vysvetleni, ktere nas napadlo je, ze $6 reprezentuje sobotu a v sobotu je "sabes" a nepracuje se :-)) 

V kazdem pripade, v puvodne domluvenem modelu predavani dat tento problem neni.
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
Předpokládám, že původním modelem myslí pan Záhořík každodenní předávání exportů dat z adresáře, ale to by šla kvůli jednomu podpoli veškerá vaše práce na API vniveč a předpokládám, že to není cesta, kterou se chceme vydat?

Veronika

**Comment by zabak** [comment]
Radek mi dnes slíbil, že ta podpole pro sobotu a neděli změní z 6 a 7 na s a n, čímž bude problém zcela vyřešen.

**Comment by honza-rychtar** [comment]
Super, s a n uz v exportu je, predelam to.
