### ISSUE TITLE
Zahodit pobocky bez nazvu a souradnic

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#27]
Nektere knihovny maji pole POB bez nazvu a mista pobocky.
Napr. 
http://info.knihovny.cz/libraries/KAG503
http://info.knihovny.cz/feeder/show/KAG503

V tomto pripade je v detailu tab "pobocky" s prazdnym obsahem.

**Comment by vodomilka** [comment]
Dívala jsem se na to, nevím,  zda by se to vyřešilo tím, že zobrazíme informace z Poznámky, které jsou vidět v záznamu v ADR, a v tomto případě se zrovna týkají poboček, nicméně tato poznámka je podle mě u pole o MVS, čili by tam mohly být i úplně jiné informace: http://aleph.nkp.cz/F/24JPRKC61REY5AVP7HR8B53PHC64VVG3VY44VTB61EI57SR2X3-39861?func=full-set-set&set_number=155715&set_entry=000001&format=030

Ve formuláři je přímo jedno pole, které se jmenuje:  
URL (přehled poboček):, kam by zrovna knihovna Havířov mohla přidat odkaz na pobočky, nicméně jsem si všimla, že MKP toto pole v ADR vyplněné má, ale na info.... se nezobrazuje. Přitom tam zřejmě není nastaven limit, na počet zobrazených webových stránek (který je např. u Národní lékařská knihovny určitě větší než u MKP).
Není to tím, že je toto pole nově přidané a nemáme jej v API?

**Comment by honza-rychtar** [comment]
Zrejme se prave to "URL (přehled poboček)" uklada do pole POB$u a ne do pole URL$u jak naznacuje umisteni ve formulari.

V MKP taky mate url pobocek v POB$u - http://info.knihovny.cz/feeder/show/abg001
POB |u http://www.mlp.cz/cz/kontakty/pobocky/

Lepsi by bylo ukladat to do URL$u s pevne danym typem viz #29 

Udelam to ted tak, ze pokud pole POB obsahuje podpole n,a,g, tak je budu brat jako ted - nazev, adresa, souradnice - vypis a zobrazeni v mape.
Pokud pole POB obsahuje pouze podpole u, tak si obsah (url) ulozim zvlast jako url pobocek a na webu bych potom nad (nebo pod?) seznamem pobocek pridal link "informace o pobockach", ktery by odkazoval na to url.
Ok?

**Comment by vodomilka** [comment]
OK, to zní rozumně, díky.
