### ISSUE TITLE
Počet zobrazených kontaktů

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#28]
Přemýšlela jsem, zda opravdu zobrazovat z adresáře všechny kontakty (mám na mysli telefonní čísla), které jsou v ADR, nebo zda je neomezit např. na 5-7 prvních čísel a ostatní nezobrazovat? A možná podobně omezit i počet zobrazovaných mailů. U některých knihoven mi to přijde příliš dlouhé, a domnívám se, že uživatele příliš zahlcujeme (předpokládám, že pokud někdo chce kontakt na mzdovou účetní z knihovny, už je s knihovnou v užším spojení).

**Comment by honza-rychtar** [comment]
Co treba u telefonu, mailu, faxu a osob zobrazit jen prvnich 5 vyskytu a pokud je jich vice nez 5, tak pod posledni (paty) zobrazeny dat "vice" - po kliku se rozbali zbyle a pod ne se prida "mene" - po kliku se zobrazi zase jen prvnich 5.
Muze byt takto?

**Comment by vodomilka** [comment]
Probírali jsme redukci zobrazených kontaktů z hlediska UX, ponechme prosím jenom první tři a nikoli více. Cílem není poskytnout kontakty na právní oddělení, zahraniční, akvizice atp., toto nejsou informace, které by uživatelé knihoven chtěli vědět, respektive není důvod tím zahlcovat všechny, když většinu to nezajímá a zdržuje při prohlížení stránky.

**Comment by vodomilka** [comment]
Zároveň bychom přestali zobrazovat i zodpovědné osoby ve výpisu kontaktů.

**Comment by vodomilka** [comment]
Na čem jsme se tedy domluvili: Zobrazovat se bude prvních 5 emailů (a tlačítko Zobraz více - pokud je co zobrazit ) a prvních 5 telefonů (a tlačítko Zobraz více - pokud je co zobrazit) . Pod tím bude další tlačítko Zobraz další kontakty a zde budou nejdříve Zodpovědné osoby a pod tím Fax (max 3 čísla a nedávala bych už možnost to dále rozbalovat).
