### ISSUE TITLE
Zobrazování odkazů

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#29]
Bylo by možné aby URL adresy, které jsou uvedené v kontaktech byly rovnou hypertext, aby si uživatelé nemuseli adresu kopírovat a vkládat do prohlížeče?
U mailových adres bych to možná ponechala ve stávající podobě bez mailto.

**Comment by vodomilka** [comment]
A k tomu ještě padl na včerejším setkání s metodiky knihoven dotaz, zda by bylo možné, aby se např. Facebook knihovny, pokud je tam vyplněno v ADR http://facebook.com/knihovnaxyz (Facebook) zobrazil jako běžná ikona Facebooku.

**Comment by honza-rychtar** [comment]
Webove stranky jsem obalil linkem.

K facebooku:
Url obsahujici facebook ma jen 16 knihoven. Z toho jen 9 u toho ma popisek (URL$z) "facebook", z toho jedna zacina na velke "F".
Navic maji 4 ruzne prefixy url:
http://www.
https://www.
https:/cs-cz.
http://facebook@

Tech 16 knihoven pouziva 7 kombinaci zapisu. A ted si predstavte, ze si "nejak" vyplni facebook tisic knihoven ...

Ja ten facebook muzu ted nejak identifikovat, ale nemuzu vedet jakymi dalsimi zpusoby to budou knihovny vyplnovat v budoucnu. 
Navic kazda dalsi sluzba, ktera bude brat data z ADR, to bude muset resit znova.

Kdyz ted delate hodne zmen v ADR bazi, tak by stalo za to rozsirit specifikaci pole URL.
Sice se snazite podle podpole URL$z nejak definovat typ ci vyznam daneho url, ale tady se bije ridici vyznam s prezentacnim.
Napr. u katalogu se z prezentacniho vyznamu - popisku - dela ridici tak, ze url je katalog, pokud je rovno "katalog", "online-katalog", "online katalog" .... ale co treba "online katalog NTK"? Bud se omezi moznost psat libovolny vlastni popisek nebo vznikne silene velka sada pravidel, ktera stejne neobsahne vsechny moznosti.

Na druhou stranu chcete identifikovat url, ktere patri webu knihovny, tak ze ma v popisku "web" - tim se ale zase orezava prezentacni vyznam - uz treba v detailu MKP je mezi webovymi strankami "http://www.mlp.cz (web)" - co je to web? Vsechno jsou to weby.

Mela by byt moznost napsat libovolnt popisek, ktery neponese zadny ridici vyznam. Tady napr. "Oficialni webove stranky knihovny".
A k tomu by mela byt moznost jednoznace urcit typ url, kde typ zase neponese zadny prezentacni vyznam.
Napr. pomoci dvou podpoli:
prezentacni podpole: URL$z - libovolny popisek, ktery slouzi k zobrazeni
ridici podpole URL&x - kod jednoznacne identifikujici typ webu/url. Vybiral by se z konecne kodove tabulky, napr.:
w - hlavni web
c - katalog
f - facebook
p - stranka pobocek
k - kramerius
t - twitter
atd.

V ADR by se rucne vkladaly popisky, ale kod by se vybiral ze seznamu - nebylo by mozne vybrat nevalidni kod, kody by byly mapovany na nazvy.

Napr. MZK by mohla mit data takto:
URL |u http://www.mzk.cz/ |z webové stránky knihovny |x w
URL |u https://vufind.mzk.cz/ |z online katalog |x c
URL |u https://www.facebook.com/mzk.cz/ |z facebook |x f
URL |u http://kramerius.mzk.cz/search/ |z digitální knihovna MZK |x k

S timhle se da krasne pracovat a staci jen rozsirit pole o jedno podpole a vytvorit kodovaci tabulku. 
@zabak rikal, ze muze byt problem pridavat do ADR veci, pro ktere bude potreba zpetne opravovat data. To by v tomto pripade nebylo potreba. Pokud URL$x nebude vyplnene, tak se nic nedeje.

**Comment by vodomilka** [comment]
Díky za rozsáhlou odpověď, navrhnu to správcům ADR, zda by to takto šlo řešit třeba v příštím roce. 
Pokud je Facebook zastoupen takto minimálně, tak bych to momentálně nechala být a neřešila žádné jeho odlišení na info.knihovny.cz, a opět to budu řešit až se správci.
