### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#3]
Muzeme vest pod MZK uctem pro GA?

**Comment by vodomilka** [comment]
Zatím žádný samostatný účet, pokud vím, zřízen není. Předpokládám, že kdyby s tím měl někdo problém, že je to pod jedním účtem, tak to vždy lze převést. Takže ano.

**Comment by zabak** [comment]
Vytvoř pro to prosím nový účet GA a nasdílej nám ho. Použijeme ho možná i pro vufind CPK. V každém případě bychom ti paralelně dodali i kódy pro piwik, který máme rozjetý pro vufind CPK.

**Comment by honza-rychtar** [comment]
Ja k tom mam GA ucet od zacatku. Slo mi o to, at to neni vedene pod mym uctem, ale pod uctem nejake instituce. Takze naopak vy vytvorte ucet a nasdilejte ho mi. Pokud to ma byt pod MZK, tak tam prava cteni mam, ale vytvaret nove sluzby nemuzu.

Proc piwik, resp. proc pouzivat paralelne dve platformy pro analytika? Jednu si vyberte a druhou zahodte.

**Comment by zabak** [comment]
Piwik máme kvůli statstikám pro zapojené knihovny do CPK - abychom měli k dispozici všechna data a mohli jim z toho poskytovat relevantní informace už přežvýkané a nerozptylovali je spoustou irelevantních informací. Ale pro zbytek MZK pracujeme s GA. Takže pohodlnost.
