### ISSUE TITLE
Opravit naseptavac

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#32]
Nove API to rozbilo

**Comment by honza-rychtar** [comment]
Pouziti naseptavaci na ostre domene: https://beta.knihovny.cz/AJAX/JSON

**Comment by vodomilka** [comment]
Jasně, podle domluvy po telefonu - toto nyní nechme být, ať to nemusíte opakovaně aktualizovat.

**Comment by honza-rychtar** [comment]
@vodomilka Ono to ted funguje - zobrazuji se vysledky jen v nazvech.
