### ISSUE TITLE
Pojmenování některých prvků

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#33]
Prosím o změnu některých označení( původní >> nové):
1. Databáze knihoven >> Vyhledat knihovnu
2. Vyhledat >> Hledat 
   ![info_knihovny_upravy](https://cloud.githubusercontent.com/assets/15191997/11930457/cc94aa90-a7e3-11e5-82ae-c3f4421c6e06.png)

**Comment by vodomilka** [comment]
Ještě k tomu připojím i změnu textu v našeptávači u vyhledání knihoven, udávejme pouze:
Zadejte město nebo název knihovny

(tj. vynecháme siglu, tu většina lidí nezná).

**Comment by vodomilka** [comment]
Prosím také o změnu názvů článků odkazující ve sloupci O projektu  na následující:

Milníky ve vývoji >> Milníky ve vývoji portálu
Zakladajici knihovny >> Zapojené knihovny

**Comment by honza-rychtar** [comment]
Opraveno
