### ISSUE TITLE
Instituce v paticce

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/AdresarKnihoven#4]
Koho tam uvest?
Ve funkcni analyze je KNAV, projekt zarizuje MKP, aplikace bezi v MZK.

**Comment by vodomilka** [comment]
A doména patří NK....  Můžeme tam v tuto chvíli uvést:

Portál knihovny.cz spravují Knihovna Akademie věd ČR, Městská knihovna v Praze, Moravská zemská knihovna a Národní knihovna ČR.

**Comment by honza-rychtar** [comment]
To je moc dlouhe.
Muzu uvest zkratky?
KNAV, MKP, MZK a NKP
Podobne jako paticka v Krameriovi - http://kramerius.mzk.cz/search/
Nebo to v paticce vubec neuvadet - informace by byla az v "O projektu"

**Comment by zabak** [comment]
Bylo by to lepší. Podobně jako to máme na betě. Základní stránka o projektu by měla být stručná a obsahovat jen pár informací a odkazy na podrobnosti - vybrané informace ze stávajícího www.knihovny.cz

**Comment by honza-rychtar** [comment]
@zabak "Bylo by to lepší" se vztahuje k tomu, aby se instituce v paticce vubec neuvadely?

**Comment by zabak** [comment]
Ano. Zkratky spoustě lidí stejně nic neřeknou a když se ty názvy rozepíšou, je z toho malý odstavec.
