### ISSUE TITLE
vyhledávání podle sigla

### ISSUE THREAD

**Issue by vodomilka** [moravianlibrary/AdresarKnihoven#5]
Bylo by možné, aby dotaz vyhledal i dotaz, kdy někdo udá siglu s mezerou PIG 001 ? Nyní se vyhledají pouze kódy bez mezery, ale přitom je někde uvádějí právě s mezerou. Ptám se, zda je možné to jednoduše řešit, pokud ne, nepovažuji to za prioritu.

**Comment by vodomilka** [comment]
A ještě k tomu mám dotaz, zda funguje vyhledávání podle kódu, když jsem zkoušela najít knihovnu ve Velkých Opatovicích, která v databázi je, podle sigly bez mezery byla nalezena, ale podle kódu, který jsem našla zde: https://www.techlib.cz/cs/2920-carove-kody-pro-ceske-knihovny/?page=9&sort=Sigla_desc (právě zde uvádějí sigla s mezerou) se mi ji nalézt nepodařilo. Je to špatný kód nebo tato část není funkční?

**Comment by honza-rychtar** [comment]
Vyhledavani pres siglu s mezerou pridam.
Vyhledavani podle kodu funguje (zkuste mkp nebo mzk) - je to pole ZKR$a, - to ale uvedena knihovna nema vyplnene.
http://aleph.nkp.cz/F/?func=direct&doc_number=000002256&local_base=ADR&format=001
